//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP1GED.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Heros()
        {
            this.InventaireHero = new HashSet<InventaireHero>();
        }
    
        public int CompteJoueurId { get; set; }
        public int Id { get; set; }
        public int Niveau { get; set; }
        public long Experience { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public decimal Argent { get; set; }
        public int StatStr { get; set; }
        public int StatDex { get; set; }
        public int StatInt { get; set; }
        public int StatVitalite { get; set; }
        public int MondeId { get; set; }
        public int ClasseId { get; set; }
        public string NomHero { get; set; }
        public bool EstConnecte { get; set; }
    
        public virtual Classe Classe { get; set; }
        public virtual CompteJoueur CompteJoueur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventaireHero> InventaireHero { get; set; }
        public virtual Monde Monde { get; set; }
    }
}
