//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP1GED.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monstre
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public int Niveau { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int StatPV { get; set; }
        public float StatDmgMin { get; set; }
        public float StatDmgMax { get; set; }
        public int MondeId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Monde Monde { get; set; }
    }
}
